### ISSUE TITLE
[Forge 14.23.5.2847] Incompatibility bug with latest version of Mysticallib (6 October)

### ISSUE THREAD

**Issue by Mythrrinthael** [SlimeKnights/TinkersToolLeveling#105]
[Here](https://pastebin.com/jkSqWiXp)'s the crashlog.

The Mysticallib devs have [this](https://i.imgur.com/YvzDk4u.png) to say about it.

**Comment by KnightMiner** [comment]
Please post a cleaner crash log, one with just the required mods to reproduce (sounds like just tool leveling, Tinkers Construct, and Mystical Lib)

**Comment by yuri0r** [comment]
cleaner [log](https://paste.ee/p/cVDqt)

short overview:
Mods:
  [✔️] Baubles-1.12-1.5.2
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mysticallib-1.12.2-1.3.8
  [✔️] MysticWorld-1.12.2-1.4.5
  [✔️] Patchouli-1.0-20
  [✔️] Roots-1.12.2-3.0.14
  [✔️] TConstruct-1.12.2-2.12.0.157
  [✔️] TinkerToolLeveling-1.12.2-1.1.0

issiu postet on [roots repo](https://github.com/MysticMods/Roots/issues/317) 

pottentially usefull insight [here](https://github.com/MysticMods/Roots/issues/317#issuecomment-538734338)

**Comment by duely** [comment]
Honestly, after a good night's sleep and reconsidering it, I might be able to fix the issue entirely just by creating a local interface to check instanceof instead of relying on the class being loaded. If that fails, I can slap `Loader.isModLoaded("mysticallib")` into the first part of the check to prevent it from trying to (potentially) load a class that's failing.

I'll test this and release 3.0.15 if it does fix it.

**Comment by duely** [comment]
I've pushed an update to CurseForge -- Roots 3.0.15 -- and, as far as I can tell, with my testing environment consisting of the following:

![](https://i.imgur.com/S5sqeY1.png)

The issue no longer occurs. My solution was to  create an empty interface and then extend from that, instead of relying on the assumption that MysticalLib would be loaded by the time attachCapability events were being called. Feel free to close this issue.

**Comment by bonii-xx** [comment]
Thanks @duely ❤️

**Comment by duely** [comment]
Although I would recommend looking into ways to prevent ItemStack creation in static initialisation as it will probably cause problems with other mods.
