### ISSUE TITLE
1.16 Update! I know it's anoying to ask but, please.

### ISSUE THREAD

**Issue by BluEagleOfficial** [SlimeKnights/TinkersToolLeveling#121]
I know people asking for new versions is really anoying, but tinkers construct just updated to 1.16, and a REALLY need this mod in my modpack!

**Comment by Mrthomas20121** [comment]
afaik there is no 1.16 port planned. however you are free to update it if you want.

**Comment by Insane96** [comment]
Actually the 1.16 mod is in alpha and can be downloaded from [here](https://www.youtube.com/watch?v=IO9XlQrEt2Y)

**Comment by sh3zb0t** [comment]
> afaik there is no 1.16 port planned. however you are free to update it if you want.



> I know people asking for new versions is really anoying, but tinkers construct just updated to 1.16, and a REALLY need this mod in my modpack!

are you both some kind of blind? have you seen releases page or curseforge page? there are already 1.16 versions

**Comment by DylanSpeiser** [comment]
Yeah, a 1.16 update would be greatly appreciated. I know it would be a lot of work coming over from 1.12, but it would be great.

**Comment by KnightMiner** [comment]
Don't ask for updates. You know its annoying, so that means you shouldn't do it. Thats like saying "I know its annoying, but I am just going to punch you".

Tinkers has been released for less than 2 weeks, and if you took 5 minutes to check, you would see the same team made this mod. Tinkers is not done, therefore why do you expect us to make you an addon because you "really need this mod in your modpack". If you really need it, update it yourself.
